development:
  adapter: mysql2
  database: destiny_development
  username: root
  password:
  host: localhost
  encoding: utf8
  collation: utf8_general_ci

test:
  adapter: mysql2
  database: destiny_test
  username: root
  password:
  host: localhost
  encoding: utf8
  collation: utf8_general_ci

production:
  adapter: mysql2
  database: destiny_prod
  username: root
  password:
  host: localhost
  encoding: utf8
  collation: utf8_general_ci
