<%
test_host = ENV['APP_SERVER_HOST'] || "localhost"
test_port = ENV['APP_SERVER_PORT'] || 8080
%>

development:
  destiny:
    host: localhost
    port: 3090

test:
  destiny:
    host: <%= test_host %>
    port: <%= test_port %>

production:
  destiny:
    scheme: https
